version: '3'
services:
  web:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - mylocal

  bd:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    container_name: database
    ports:
        - "127.0.0.1:5432:5432"
    networks:
      - mylocal
networks:
  mylocal:
    driver: bridge

